name: Deploy to OpenShift
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: shrijandra/demo-app

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Fix git safe directory
        shell: cmd
        run: git config --global --add safe.directory *

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
          persist-credentials: false
          fetch-depth: 1
          submodules: false      # ← add this — disables the sh -c submodule commands

      - name: Login to Container Registry
        shell: cmd
        run: echo ${{ secrets.REGISTRY_PASSWORD }}| docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Image
        shell: cmd
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest

      - name: Login to OpenShift
        shell: cmd
        run: oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify=true

      - name: Deploy App
        shell: pwsh
        run: |
          $FULL_TAG="${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest"
          (Get-Content deployment.yaml).Replace('IMAGE_PLACEHOLDER', $FULL_TAG) | Set-Content deployment.yaml
          oc apply -f deployment.yaml
          oc apply -f service.yaml
          oc apply -f route.yaml
